//! jj-lib 0.42 GitBackend oracle for the frozen kernel Git vectors.
//!
//! Regenerate from the workspace root with
//! `nix develop -c cargo run -p devspace-kernel-oracle --bin kernel-oracle`.
//! The fixture fixes identities and timestamps. Its throwaway Ed25519 key is
//! generated on each run and signs both a commit and the merged annotated tag,
//! so those two signature-bearing vectors change.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::{self, Read, Write as _};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use devspace_kernel::ops::{OpObjectKind, validate_op};
use devspace_kernel::{
    ObjectKind, Oid, ReferenceKind, TreeEntryKind, parse_commit, parse_tree, validate,
};
use devspace_machine::MachineGitRepository;
use futures::executor::block_on;
use jj_lib::backend::{
    Backend as _, ChangeId, Commit as BackendCommit, CommitId, MillisSinceEpoch, Signature,
    Timestamp, TreeId,
};
use jj_lib::config::{ConfigLayer, ConfigSource, StackedConfig};
use jj_lib::git_backend::GitBackend;
use jj_lib::merge::Merge;
use jj_lib::object_id::ObjectId as _;
use jj_lib::op_store::{RefTarget, RemoteRef, RemoteRefState};
use jj_lib::ref_name::{RefName, RemoteRefSymbol};
use jj_lib::repo::Repo as _;
use jj_lib::settings::UserSettings;
use tempfile::TempDir;

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

const BASE_TIME: i64 = 1_700_000_000;
const GENERATED_HEADER: &str = "# Generated by: nix develop -c cargo run -p devspace-kernel-oracle --bin kernel-oracle\n# Format: <type>|<expected SHA-1>|<raw payload as lowercase hex>\n# Identities and timestamps are fixed. The SSH-signed commit and signed-tag mergetag vectors are intentionally nondeterministic.\n";

#[derive(Clone, Debug)]
struct Object {
    kind: ObjectKind,
    oid: Oid,
    payload: Vec<u8>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Report {
    pub walked: usize,
    pub commits: usize,
    pub trees: usize,
    pub blobs: usize,
    pub curated: usize,
    pub signed_commit: bool,
    pub op_ported: usize,
    pub op_regenerated_views: usize,
    pub op_regenerated_operations: usize,
}

struct Fixture {
    _temp: TempDir,
    backend: GitBackend,
    git_dir: PathBuf,
    feature_oids: BTreeMap<Oid, &'static str>,
    signed_commit: bool,
}

impl Fixture {
    fn new() -> Result<Self> {
        let temp = tempfile::tempdir()?;
        let store_path = temp.path().join("store");
        fs::create_dir(&store_path)?;
        let backend = GitBackend::init_internal(&settings(), &store_path)?;
        let git_dir = backend.git_repo_path().to_owned();
        let mut fixture = Self {
            _temp: temp,
            backend,
            git_dir,
            feature_oids: BTreeMap::new(),
            signed_commit: false,
        };
        fixture.configure_git()?;
        fixture.build()?;
        Ok(fixture)
    }

    fn configure_git(&self) -> Result<()> {
        self.git(&["config", "user.name", "Git Oracle"], None, BASE_TIME)?;
        self.git(
            &["config", "user.email", "oracle@example.invalid"],
            None,
            BASE_TIME,
        )?;
        Ok(())
    }

    fn build(&mut self) -> Result<()> {
        let empty_blob = self.hash_object("blob", b"")?;
        self.mark(empty_blob, "empty blob");
        let base_blob = self.hash_object("blob", b"base\n")?;
        self.mark(base_blob, "regular file blob");
        let executable_blob = self.hash_object("blob", b"#!/bin/sh\necho oracle\n")?;
        self.mark(executable_blob, "executable blob");
        let symlink_blob = self.hash_object("blob", b"nested/data.txt")?;
        self.mark(symlink_blob, "symlink target blob");
        let binary_blob = self.hash_object("blob", b"binary\0payload\xff\n")?;
        self.mark(binary_blob, "binary blob");

        let empty_tree = self.mktree(&[])?;
        self.mark(empty_tree, "empty tree");
        let nested_tree = self.mktree(&[
            TreeSpec::blob("100644", "data.txt", binary_blob),
            TreeSpec::blob("100644", "empty", empty_blob),
        ])?;
        self.mark(nested_tree, "nested tree");
        let base_tree = self.mktree(&[TreeSpec::blob("100644", "base.txt", base_blob)])?;
        self.mark(base_tree, "single-file tree");
        let mixed_tree = self.mktree(&[
            TreeSpec::tree("40000", "empty-dir", empty_tree),
            TreeSpec::blob("100755", "oracle.sh", executable_blob),
            TreeSpec::blob("120000", "oracle-link", symlink_blob),
            TreeSpec::tree("40000", "nested", nested_tree),
            TreeSpec::blob("100644", "regular.txt", base_blob),
        ])?;
        self.mark(mixed_tree, "mixed-mode root tree");

        let mut large_entries = Vec::new();
        for index in 0..128_u16 {
            let content = vec![b'x'; usize::from(index) + 1];
            let oid = self.hash_object("blob", &content)?;
            if index.is_power_of_two() || index == 127 {
                self.mark(oid, "large-tree blob size boundary");
            }
            large_entries.push(TreeSpec::blob(
                "100644",
                format!("entry-{index:03}.txt"),
                oid,
            ));
        }
        let large_tree = self.mktree(&large_entries)?;
        self.mark(large_tree, "large tree with 128 entries");

        let root = self.commit_tree(base_tree, &[], b"root\n", BASE_TIME + 1, false)?;
        self.mark(root, "root commit");
        let linear_one =
            self.commit_tree(mixed_tree, &[root], b"linear one\n", BASE_TIME + 2, false)?;
        self.mark(linear_one, "linear commit");
        let linear_two = self.commit_tree(
            large_tree,
            &[linear_one],
            b"linear two\n",
            BASE_TIME + 3,
            false,
        )?;
        self.mark(linear_two, "linear large-tree commit");

        let side_one_tree = self.mktree(&[
            TreeSpec::blob("100644", "base.txt", base_blob),
            TreeSpec::blob("100644", "side-one.txt", executable_blob),
        ])?;
        let side_two_tree = self.mktree(&[
            TreeSpec::blob("100644", "base.txt", base_blob),
            TreeSpec::blob("100644", "side-two.txt", binary_blob),
            TreeSpec::tree("40000", "nested", nested_tree),
        ])?;
        let side_one =
            self.commit_tree(side_one_tree, &[root], b"side one\n", BASE_TIME + 4, false)?;
        let side_two =
            self.commit_tree(side_two_tree, &[root], b"side two\n", BASE_TIME + 5, false)?;
        let merge = self.commit_tree(
            mixed_tree,
            &[linear_two, side_one],
            b"two-parent merge\n",
            BASE_TIME + 6,
            false,
        )?;
        self.mark(merge, "merge commit");
        let octopus = self.commit_tree(
            mixed_tree,
            &[linear_two, side_one, side_two],
            b"octopus merge\n",
            BASE_TIME + 7,
            false,
        )?;
        self.mark(octopus, "octopus merge commit");

        let encoding = self.write_raw_commit(raw_commit(
            large_tree,
            &[linear_two],
            Some(b"encoding ISO-8859-1\n"),
            b"Encoded Author",
            b"encoded message \xe9\n",
            BASE_TIME + 8,
        ))?;
        self.mark(encoding, "encoding-header commit");
        let non_utf8 = self.write_raw_commit(raw_commit(
            mixed_tree,
            &[encoding],
            None,
            b"Non-UTF-8 \xff Author",
            b"non-UTF-8 message \xfe\n",
            BASE_TIME + 9,
        ))?;
        self.mark(non_utf8, "non-UTF-8 commit metadata");

        if let Some(signed) = self.signed_commit(mixed_tree, linear_two, BASE_TIME + 10)? {
            self.mark(signed, "SSH-signed commit");
            self.update_ref("refs/heads/signed", signed)?;
            self.signed_commit = true;
        }

        let tag_target = self.commit_tree(
            side_one_tree,
            &[linear_two],
            b"annotated tag target\n",
            BASE_TIME + 11,
            false,
        )?;
        self.update_ref("refs/heads/tag-target", tag_target)?;
        let tag_mode = if self.signed_commit { "-s" } else { "-a" };
        self.git(
            &[
                "tag",
                tag_mode,
                "oracle-v1",
                "-m",
                "oracle annotated tag",
                &oid_hex(tag_target),
            ],
            None,
            BASE_TIME + 12,
        )?;
        let tag_oid = self.rev_parse("refs/tags/oracle-v1")?;
        let git_merge = self.merge_annotated_tag(linear_two, BASE_TIME + 13)?;
        let mergetag = if self.signed_commit {
            git_merge
        } else {
            let merge_payload = self.cat_file("commit", git_merge)?;
            let tag_payload = self.cat_file("tag", tag_oid)?;
            self.write_raw_commit(with_mergetag(&merge_payload, &tag_payload)?)?
        };
        self.mark(mergetag, "annotated-tag merge with mergetag");

        for (name, oid) in [
            ("root", root),
            ("linear", linear_two),
            ("merge", merge),
            ("octopus", octopus),
            ("encoding", encoding),
            ("non-utf8", non_utf8),
            ("mergetag", mergetag),
        ] {
            self.update_ref(&format!("refs/heads/{name}"), oid)?;
        }

        let change_commit = self.write_jj_commit(
            Merge::resolved(String::new()),
            Merge::resolved(TreeId::from_bytes(&large_tree.0)),
            ChangeId::from_bytes(&[0x12; 16]),
            vec![CommitId::from_bytes(&linear_two.0)],
            "jj change-id commit",
            BASE_TIME + 14,
        )?;
        self.mark(change_commit, "jj change-id commit");
        self.update_ref("refs/heads/jj-change", change_commit)?;

        let conflict_commit = self.write_jj_commit(
            Merge::from_vec(vec![
                "left".to_owned(),
                "base".to_owned(),
                "right".to_owned(),
            ]),
            Merge::from_vec(vec![
                TreeId::from_bytes(&mixed_tree.0),
                TreeId::from_bytes(&base_tree.0),
                TreeId::from_bytes(&large_tree.0),
            ]),
            ChangeId::from_bytes(&[0x34; 16]),
            vec![CommitId::from_bytes(&change_commit.0)],
            "jj conflicted commit",
            BASE_TIME + 15,
        )?;
        self.mark(conflict_commit, "jj conflicted commit with labels");
        self.update_ref("refs/heads/jj-conflict", conflict_commit)?;

        Ok(())
    }

    fn mark(&mut self, oid: Oid, feature: &'static str) {
        self.feature_oids.insert(oid, feature);
    }

    fn git(&self, args: &[&str], input: Option<&[u8]>, timestamp: i64) -> Result<Vec<u8>> {
        let mut command = self.git_command(timestamp);
        command
            .arg("--git-dir")
            .arg(&self.git_dir)
            .args(args)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());
        if input.is_some() {
            command.stdin(Stdio::piped());
        }
        let mut child = command.spawn()?;
        if let Some(bytes) = input {
            child.stdin.take().expect("piped stdin").write_all(bytes)?;
        }
        let output = child.wait_with_output()?;
        if !output.status.success() {
            return Err(io::Error::other(format!(
                "git {} failed: {}",
                args.join(" "),
                String::from_utf8_lossy(&output.stderr).trim()
            ))
            .into());
        }
        Ok(output.stdout)
    }

    fn git_command(&self, timestamp: i64) -> Command {
        let mut command = Command::new("git");
        command
            .env("GIT_AUTHOR_NAME", "Git Oracle")
            .env("GIT_AUTHOR_EMAIL", "oracle@example.invalid")
            .env("GIT_AUTHOR_DATE", format!("@{timestamp} +0000"))
            .env("GIT_COMMITTER_NAME", "Git Oracle")
            .env("GIT_COMMITTER_EMAIL", "oracle@example.invalid")
            .env("GIT_COMMITTER_DATE", format!("@{timestamp} +0000"))
            .env("GIT_CONFIG_NOSYSTEM", "1")
            .env("GIT_CONFIG_GLOBAL", "/dev/null")
            .env("LC_ALL", "C")
            .env("TZ", "UTC");
        command
    }

    fn merge_annotated_tag(&self, start: Oid, timestamp: i64) -> Result<Oid> {
        let worktree = self._temp.path().join("mergetag-worktree");
        let worktree_text = worktree
            .to_str()
            .ok_or_else(|| io::Error::other("non-UTF-8 worktree path"))?;
        self.git(
            &[
                "worktree",
                "add",
                "--detach",
                worktree_text,
                &oid_hex(start),
            ],
            None,
            timestamp,
        )?;
        let output = self
            .git_command(timestamp)
            .arg("-C")
            .arg(&worktree)
            .args([
                "merge",
                "--no-ff",
                "--no-edit",
                "-m",
                "merge annotated tag oracle-v1",
                "oracle-v1",
            ])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()?;
        if !output.status.success() {
            return Err(io::Error::other(format!(
                "git merge annotated tag failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ))
            .into());
        }
        let output = self
            .git_command(timestamp)
            .arg("-C")
            .arg(worktree)
            .args(["rev-parse", "HEAD"])
            .output()?;
        if !output.status.success() {
            return Err(io::Error::other("git rev-parse after tag merge failed").into());
        }
        parse_oid(&output.stdout)
    }

    fn hash_object(&self, kind: &str, payload: &[u8]) -> Result<Oid> {
        parse_oid(&self.git(
            &["hash-object", "-w", "-t", kind, "--stdin"],
            Some(payload),
            BASE_TIME,
        )?)
    }

    fn mktree(&self, entries: &[TreeSpec]) -> Result<Oid> {
        let mut input = Vec::new();
        for entry in entries {
            write!(
                input,
                "{} {} {}\t",
                entry.mode,
                entry.kind,
                oid_hex(entry.oid)
            )?;
            input.extend_from_slice(entry.name.as_bytes());
            input.push(0);
        }
        parse_oid(&self.git(&["mktree", "-z"], Some(&input), BASE_TIME)?)
    }

    fn commit_tree(
        &self,
        tree: Oid,
        parents: &[Oid],
        message: &[u8],
        timestamp: i64,
        signed: bool,
    ) -> Result<Oid> {
        let mut owned = vec!["commit-tree".to_owned()];
        if signed {
            owned.push("-S".to_owned());
        }
        owned.push(oid_hex(tree));
        for parent in parents {
            owned.push("-p".to_owned());
            owned.push(oid_hex(*parent));
        }
        let args = owned.iter().map(String::as_str).collect::<Vec<_>>();
        parse_oid(&self.git(&args, Some(message), timestamp)?)
    }

    fn write_raw_commit(&self, payload: Vec<u8>) -> Result<Oid> {
        self.hash_object("commit", &payload)
    }

    fn signed_commit(&self, tree: Oid, parent: Oid, timestamp: i64) -> Result<Option<Oid>> {
        let key_path = self._temp.path().join("oracle-signing-key");
        let output = match Command::new("ssh-keygen")
            .args(["-q", "-t", "ed25519", "-N", "", "-C", "git-oracle", "-f"])
            .arg(&key_path)
            .output()
        {
            Ok(output) => output,
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                eprintln!(
                    "LOUD NOTICE: ssh-keygen is unavailable; SSH-signed commit coverage is skipped"
                );
                return Ok(None);
            }
            Err(error) => return Err(error.into()),
        };
        if !output.status.success() {
            return Err(io::Error::other(format!(
                "ssh-keygen failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ))
            .into());
        }
        self.git(&["config", "gpg.format", "ssh"], None, timestamp)?;
        self.git(
            &[
                "config",
                "user.signingkey",
                key_path
                    .to_str()
                    .ok_or_else(|| io::Error::other("non-UTF-8 key path"))?,
            ],
            None,
            timestamp,
        )?;
        self.commit_tree(tree, &[parent], b"SSH-signed commit\n", timestamp, true)
            .map(Some)
    }

    #[allow(clippy::too_many_arguments)]
    fn write_jj_commit(
        &self,
        conflict_labels: Merge<String>,
        root_tree: Merge<TreeId>,
        change_id: ChangeId,
        parents: Vec<CommitId>,
        description: &str,
        timestamp: i64,
    ) -> Result<Oid> {
        let signature = Signature {
            name: "jj Oracle".to_owned(),
            email: "jj-oracle@example.invalid".to_owned(),
            timestamp: Timestamp {
                timestamp: MillisSinceEpoch(timestamp * 1000),
                tz_offset: 0,
            },
        };
        let commit = BackendCommit {
            parents,
            predecessors: Vec::new(),
            root_tree,
            conflict_labels,
            change_id,
            description: description.to_owned(),
            author: signature.clone(),
            committer: signature,
            secure_sig: None,
        };
        let (id, _) = block_on(self.backend.write_commit(commit, None))?;
        Oid::from_bytes(id.as_bytes()).ok_or_else(|| io::Error::other("non-SHA-1 jj commit").into())
    }

    fn update_ref(&self, name: &str, oid: Oid) -> Result<()> {
        self.git(&["update-ref", name, &oid_hex(oid)], None, BASE_TIME)?;
        Ok(())
    }

    fn rev_parse(&self, name: &str) -> Result<Oid> {
        parse_oid(&self.git(&["rev-parse", name], None, BASE_TIME)?)
    }

    fn cat_file(&self, kind: &str, oid: Oid) -> Result<Vec<u8>> {
        self.git(&["cat-file", kind, &oid_hex(oid)], None, BASE_TIME)
    }

    fn reachable_oids(&self) -> Result<Vec<Oid>> {
        let output = self.git(&["rev-list", "--objects", "--all"], None, BASE_TIME)?;
        output
            .split(|byte| *byte == b'\n')
            .filter(|line| !line.is_empty())
            .map(|line| {
                let hex = line.split(|byte| *byte == b' ').next().unwrap_or_default();
                Oid::from_hex(hex).ok_or_else(|| io::Error::other("invalid rev-list oid").into())
            })
            .collect()
    }

    fn batch_objects(&self) -> Result<Vec<Object>> {
        let oids = self.reachable_oids()?;
        let mut child = Command::new("git")
            .arg("--git-dir")
            .arg(&self.git_dir)
            .args(["cat-file", "--batch"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()?;
        {
            let mut stdin = child.stdin.take().expect("piped stdin");
            for oid in &oids {
                writeln!(stdin, "{}", oid_hex(*oid))?;
            }
        }
        let output = child.wait_with_output()?;
        if !output.status.success() {
            return Err(io::Error::other(format!(
                "git cat-file --batch failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ))
            .into());
        }
        let mut cursor = io::Cursor::new(output.stdout);
        let mut objects = Vec::new();
        for expected in oids {
            let header = read_line(&mut cursor)?;
            let fields = header.split(|byte| *byte == b' ').collect::<Vec<_>>();
            if fields.len() != 3 {
                return Err(io::Error::other("invalid cat-file batch header").into());
            }
            let actual = Oid::from_hex(fields[0])
                .ok_or_else(|| io::Error::other("invalid batch object id"))?;
            if actual != expected {
                return Err(io::Error::other("cat-file changed object order").into());
            }
            let size = std::str::from_utf8(fields[2])?.parse::<usize>()?;
            let mut payload = vec![0; size];
            cursor.read_exact(&mut payload)?;
            let mut newline = [0];
            cursor.read_exact(&mut newline)?;
            if newline != *b"\n" {
                return Err(io::Error::other("cat-file payload lacks separator").into());
            }
            let kind = match fields[1] {
                b"blob" => Some(ObjectKind::Blob),
                b"tree" => Some(ObjectKind::Tree),
                b"commit" => Some(ObjectKind::Commit),
                b"tag" => None,
                other => {
                    return Err(io::Error::other(format!(
                        "unexpected reachable object type {}",
                        String::from_utf8_lossy(other)
                    ))
                    .into());
                }
            };
            if let Some(kind) = kind {
                objects.push(Object {
                    kind,
                    oid: actual,
                    payload,
                });
            }
        }
        objects.sort_by_key(|object| (object.kind, object.oid));
        Ok(objects)
    }

    fn pretty(&self, oid: Oid) -> Result<Vec<u8>> {
        self.git(&["cat-file", "-p", &oid_hex(oid)], None, BASE_TIME)
    }
}

struct TreeSpec {
    mode: &'static str,
    kind: &'static str,
    name: String,
    oid: Oid,
}

impl TreeSpec {
    fn blob(mode: &'static str, name: impl Into<String>, oid: Oid) -> Self {
        Self {
            mode,
            kind: "blob",
            name: name.into(),
            oid,
        }
    }

    fn tree(mode: &'static str, name: impl Into<String>, oid: Oid) -> Self {
        Self {
            mode,
            kind: "tree",
            name: name.into(),
            oid,
        }
    }
}

pub fn generate(write_vectors: bool) -> Result<Report> {
    let fixture = Fixture::new()?;
    let objects = fixture.batch_objects()?;
    assert_fixture_coverage(&objects, fixture.signed_commit)?;
    for object in &objects {
        validate_object(&fixture, object)?;
    }
    let curated = curate(&objects, &fixture.feature_oids)?;
    let contents = render(&curated);
    if write_vectors {
        fs::write(vector_path(), contents)?;
    }
    let op_report = generate_op_vectors(write_vectors)?;
    Ok(Report {
        walked: objects.len(),
        commits: objects
            .iter()
            .filter(|object| object.kind == ObjectKind::Commit)
            .count(),
        trees: objects
            .iter()
            .filter(|object| object.kind == ObjectKind::Tree)
            .count(),
        blobs: objects
            .iter()
            .filter(|object| object.kind == ObjectKind::Blob)
            .count(),
        curated: curated.len(),
        signed_commit: fixture.signed_commit,
        op_ported: op_report.ported,
        op_regenerated_views: op_report.views,
        op_regenerated_operations: op_report.operations,
    })
}

struct OpReport {
    ported: usize,
    views: usize,
    operations: usize,
}

fn generate_op_vectors(write_vectors: bool) -> Result<OpReport> {
    let temp = tempfile::tempdir()?;
    let repository = block_on(MachineGitRepository::init(temp.path(), &settings()))?;
    let mut repo = repository.repo().clone();
    for name in ["alpha", "beta", "gamma"] {
        let mut transaction = repo.start_transaction();
        transaction.repo_mut().set_remote_bookmark(
            RemoteRefSymbol {
                name: RefName::new(name),
                remote: "origin".as_ref(),
            },
            RemoteRef {
                target: RefTarget::normal(repo.store().root_commit_id().clone()),
                state: RemoteRefState::New,
            },
        );
        repo = block_on(transaction.commit(format!("GitBackend oracle {name}")))?;
    }

    let mut generated = Vec::new();
    for (kind, directory) in [
        (OpObjectKind::View, "views"),
        (OpObjectKind::Operation, "operations"),
    ] {
        let mut entries = fs::read_dir(repository.operation_store_path().join(directory))?
            .collect::<io::Result<Vec<_>>>()?;
        entries.sort_unstable_by_key(|entry| entry.file_name());
        for entry in entries {
            let bytes = fs::read(entry.path())?;
            let validated = validate_op(kind, &bytes)?;
            let filename = entry.file_name();
            let filename = filename
                .to_str()
                .ok_or_else(|| io::Error::other("non-UTF-8 operation-store ID"))?;
            if filename != encode_hex(&validated.id) {
                return Err(io::Error::other("jj-lib operation-store filename changed").into());
            }
            generated.push((kind, validated.id, bytes));
        }
    }
    generated.sort_unstable_by_key(|(kind, id, _)| (*kind as u8, *id));

    let ported = include_str!("../../kernel/tests/ops_golden.txt")
        .lines()
        .filter(|line| line.starts_with("operation|"))
        .take(2)
        .collect::<Vec<_>>();
    let mut output = String::from(
        "# Generated by kernel-oracle. Two operation vectors are ported unchanged; GitBackend views and operations are regenerated through jj-lib 0.42.\n",
    );
    for line in &ported {
        output.push_str(line);
        output.push('\n');
    }
    for (kind, id, bytes) in &generated {
        output.push_str(match kind {
            OpObjectKind::View => "view",
            OpObjectKind::Operation => "operation",
        });
        output.push('|');
        output.push_str(&encode_hex(id));
        output.push('|');
        output.push_str(&encode_rle(bytes));
        output.push('\n');
    }
    if write_vectors {
        fs::write(op_vector_path(), output)?;
    }
    Ok(OpReport {
        ported: ported.len(),
        views: generated
            .iter()
            .filter(|(kind, _, _)| *kind == OpObjectKind::View)
            .count(),
        operations: generated
            .iter()
            .filter(|(kind, _, _)| *kind == OpObjectKind::Operation)
            .count(),
    })
}

fn validate_object(fixture: &Fixture, object: &Object) -> Result<()> {
    let validated = validate(object.kind, &object.payload).map_err(|error| {
        io::Error::other(format!(
            "kernel rejected {} {}: {error}",
            kind_name(object.kind),
            oid_hex(object.oid)
        ))
    })?;
    if validated.id != object.oid {
        return Err(
            io::Error::other(format!("kernel ID mismatch for {}", oid_hex(object.oid))).into(),
        );
    }
    let pretty = fixture.pretty(object.oid)?;
    match object.kind {
        ObjectKind::Blob => {
            if !validated.references.is_empty() {
                return Err(io::Error::other("blob exposed references").into());
            }
        }
        ObjectKind::Tree => {
            let expected = pretty_tree_references(&pretty)?;
            let actual = validated
                .references
                .iter()
                .map(|reference| (reference.kind, reference.id))
                .collect::<BTreeSet<_>>();
            if actual != expected {
                return Err(io::Error::other(format!(
                    "tree references disagree with git cat-file for {}",
                    oid_hex(object.oid)
                ))
                .into());
            }
        }
        ObjectKind::Commit => {
            let parsed = parse_commit(&object.payload)?;
            let (git_tree, git_parents) = pretty_commit_references(&pretty)?;
            let mut expected = BTreeSet::from([(ReferenceKind::Tree, git_tree)]);
            expected.extend(git_parents.iter().map(|oid| (ReferenceKind::Commit, *oid)));
            expected.extend(
                parsed
                    .jj_trees
                    .iter()
                    .map(|oid| (ReferenceKind::Tree, *oid)),
            );
            let actual = validated
                .references
                .iter()
                .map(|reference| (reference.kind, reference.id))
                .collect::<BTreeSet<_>>();
            if actual != expected {
                return Err(io::Error::other(format!(
                    "commit reference extraction disagrees with git cat-file for {}",
                    oid_hex(object.oid)
                ))
                .into());
            }
            validate_commit(fixture, object, parsed, git_tree, git_parents)?;
        }
    }
    Ok(())
}

fn validate_commit(
    fixture: &Fixture,
    object: &Object,
    parsed: devspace_kernel::Commit<'_>,
    git_tree: Oid,
    git_parents: Vec<Oid>,
) -> Result<()> {
    if parsed.tree != git_tree || parsed.parents != git_parents {
        return Err(io::Error::other(format!(
            "commit references disagree with git cat-file for {}",
            oid_hex(object.oid)
        ))
        .into());
    }
    let backend_commit = block_on(
        fixture
            .backend
            .read_commit(&CommitId::from_bytes(&object.oid.0)),
    )?;
    if let Some(change_id) = parsed.change_id
        && backend_commit.change_id.as_bytes() != change_id
    {
        return Err(io::Error::other(format!(
            "change-id disagrees with jj-lib for {}",
            oid_hex(object.oid)
        ))
        .into());
    }
    let jj_trees = backend_commit
        .root_tree
        .as_slice()
        .iter()
        .map(|id| Oid::from_bytes(id.as_bytes()).expect("SHA-1 GitBackend tree"))
        .collect::<Vec<_>>();
    let expected_trees = if parsed.jj_trees.is_empty() {
        vec![parsed.tree]
    } else {
        parsed.jj_trees.clone()
    };
    if jj_trees != expected_trees {
        return Err(io::Error::other(format!(
            "jj:trees disagrees with jj-lib for {}",
            oid_hex(object.oid)
        ))
        .into());
    }
    let jj_labels = if backend_commit.conflict_labels.is_resolved() {
        Vec::new()
    } else {
        backend_commit
            .conflict_labels
            .as_slice()
            .iter()
            .map(String::as_str)
            .collect::<Vec<_>>()
    };
    let expected_labels = parsed.conflict_labels.unwrap_or_default();
    if jj_labels != expected_labels {
        return Err(io::Error::other(format!(
            "conflict labels disagree with jj-lib for {}",
            oid_hex(object.oid)
        ))
        .into());
    }
    Ok(())
}

fn assert_fixture_coverage(objects: &[Object], signed_commit: bool) -> Result<()> {
    let commits = objects
        .iter()
        .filter(|object| object.kind == ObjectKind::Commit)
        .map(|object| parse_commit(&object.payload))
        .collect::<std::result::Result<Vec<_>, _>>()?;
    let trees = objects
        .iter()
        .filter(|object| object.kind == ObjectKind::Tree)
        .map(|object| parse_tree(&object.payload))
        .collect::<std::result::Result<Vec<_>, _>>()?;

    let has_header = |name: &[u8]| {
        commits
            .iter()
            .any(|commit| commit.headers.iter().any(|header| header.name == name))
    };
    let required = [
        commits.iter().any(|commit| commit.parents.len() == 1),
        commits.iter().any(|commit| commit.parents.len() == 2),
        commits.iter().any(|commit| commit.parents.len() >= 3),
        has_header(b"encoding"),
        has_header(b"mergetag"),
        has_header(b"change-id"),
        has_header(b"jj:trees"),
        commits
            .iter()
            .any(|commit| commit.conflict_labels.is_some()),
        commits
            .iter()
            .any(|commit| !commit.author.name.is_ascii() && !commit.message.is_ascii()),
        trees.iter().any(|tree| tree.entries.is_empty()),
        trees.iter().any(|tree| tree.entries.len() > 100),
        trees.iter().any(|tree| {
            let kinds = tree
                .entries
                .iter()
                .map(|entry| entry.kind)
                .collect::<BTreeSet<_>>();
            kinds.contains(&TreeEntryKind::Executable)
                && kinds.contains(&TreeEntryKind::Symlink)
                && kinds.contains(&TreeEntryKind::Tree)
        }),
    ];
    let requirement_names = [
        "linear commit",
        "merge commit",
        "octopus commit",
        "encoding header",
        "mergetag header",
        "change-id header",
        "jj:trees header",
        "conflict labels",
        "non-UTF-8 metadata",
        "empty tree",
        "large tree",
        "mixed-mode tree",
    ];
    if let Some((index, _)) = required.iter().enumerate().find(|(_, covered)| !*covered) {
        return Err(io::Error::other(format!(
            "fixture lost required coverage: {}",
            requirement_names[index]
        ))
        .into());
    }
    if signed_commit && !has_header(b"gpgsig") {
        return Err(io::Error::other("SSH-signed fixture commit lacks gpgsig header").into());
    }
    Ok(())
}

fn curate<'a>(
    objects: &'a [Object],
    features: &BTreeMap<Oid, &'static str>,
) -> Result<Vec<&'a Object>> {
    let mut by_shape = BTreeMap::<String, &Object>::new();
    for object in objects {
        let shape = shape(object, features)?;
        by_shape.entry(shape).or_insert(object);
    }
    let mut curated = by_shape.into_values().collect::<Vec<_>>();
    curated.sort_by_key(|object| (object.kind, object.oid));
    Ok(curated)
}

fn shape(object: &Object, features: &BTreeMap<Oid, &'static str>) -> Result<String> {
    if let Some(feature) = features.get(&object.oid) {
        return Ok(format!("feature:{feature}"));
    }
    match object.kind {
        ObjectKind::Blob => {
            let size_bucket = if object.payload.is_empty() {
                0
            } else {
                usize::BITS - object.payload.len().leading_zeros()
            };
            Ok(format!(
                "blob:{size_bucket}:{}",
                object.payload.contains(&0)
            ))
        }
        ObjectKind::Tree => {
            let tree = parse_tree(&object.payload)?;
            let mut modes = [0_usize; 5];
            for entry in &tree.entries {
                let index = match entry.kind {
                    TreeEntryKind::File => 0,
                    TreeEntryKind::Executable => 1,
                    TreeEntryKind::Symlink => 2,
                    TreeEntryKind::Tree => 3,
                    TreeEntryKind::Gitlink => 4,
                };
                modes[index] += 1;
            }
            Ok(format!("tree:{}:{modes:?}", tree.entries.len()))
        }
        ObjectKind::Commit => {
            let commit = parse_commit(&object.payload)?;
            let headers = commit
                .headers
                .iter()
                .map(|header| String::from_utf8_lossy(header.name))
                .collect::<Vec<_>>()
                .join(",");
            Ok(format!(
                "commit:{}:{headers}:{}:{}",
                commit.parents.len(),
                commit.author.name.is_ascii(),
                commit.message.is_ascii()
            ))
        }
    }
}

fn render(objects: &[&Object]) -> String {
    let mut output = GENERATED_HEADER.to_owned();
    for object in objects {
        output.push_str(kind_name(object.kind));
        output.push('|');
        output.push_str(&oid_hex(object.oid));
        output.push('|');
        output.push_str(&encode_hex(&object.payload));
        output.push('\n');
    }
    output
}

fn settings() -> UserSettings {
    let mut config = StackedConfig::with_defaults();
    config.add_layer(
        ConfigLayer::parse(
            ConfigSource::User,
            r#"
                [user]
                name = "jj Oracle"
                email = "jj-oracle@example.invalid"

                [git]
                write-change-id-header = true
            "#,
        )
        .expect("static oracle config"),
    );
    UserSettings::from_config(config).expect("static oracle settings")
}

fn raw_commit(
    tree: Oid,
    parents: &[Oid],
    extra_header: Option<&[u8]>,
    author_name: &[u8],
    message: &[u8],
    timestamp: i64,
) -> Vec<u8> {
    let mut payload = Vec::new();
    writeln!(payload, "tree {}", oid_hex(tree)).expect("Vec write");
    for parent in parents {
        writeln!(payload, "parent {}", oid_hex(*parent)).expect("Vec write");
    }
    payload.extend_from_slice(b"author ");
    payload.extend_from_slice(author_name);
    writeln!(payload, " <oracle@example.invalid> {timestamp} +0000").expect("Vec write");
    writeln!(
        payload,
        "committer Git Oracle <oracle@example.invalid> {timestamp} +0000"
    )
    .expect("Vec write");
    if let Some(header) = extra_header {
        payload.extend_from_slice(header);
    }
    payload.push(b'\n');
    payload.extend_from_slice(message);
    payload
}

fn with_mergetag(commit: &[u8], tag: &[u8]) -> Result<Vec<u8>> {
    let header_end = commit
        .windows(2)
        .position(|window| window == b"\n\n")
        .ok_or_else(|| io::Error::other("Git merge commit lacks header terminator"))?;
    let mut payload = Vec::with_capacity(commit.len() + tag.len() + 16);
    payload.extend_from_slice(&commit[..header_end]);
    payload.extend_from_slice(b"\nmergetag ");
    let mut lines = tag.split(|byte| *byte == b'\n');
    payload.extend_from_slice(lines.next().unwrap_or_default());
    payload.push(b'\n');
    for line in lines {
        payload.push(b' ');
        payload.extend_from_slice(line);
        payload.push(b'\n');
    }
    payload.extend_from_slice(&commit[header_end + 1..]);
    Ok(payload)
}

fn pretty_commit_references(payload: &[u8]) -> Result<(Oid, Vec<Oid>)> {
    let mut tree = None;
    let mut parents = Vec::new();
    for line in payload.split(|byte| *byte == b'\n') {
        if line.is_empty() {
            break;
        }
        if let Some(hex) = line.strip_prefix(b"tree ") {
            tree = Oid::from_hex(hex);
        } else if let Some(hex) = line.strip_prefix(b"parent ") {
            parents.push(
                Oid::from_hex(hex)
                    .ok_or_else(|| io::Error::other("invalid cat-file parent oid"))?,
            );
        }
    }
    Ok((
        tree.ok_or_else(|| io::Error::other("cat-file commit lacks tree"))?,
        parents,
    ))
}

fn pretty_tree_references(payload: &[u8]) -> Result<BTreeSet<(ReferenceKind, Oid)>> {
    payload
        .split(|byte| *byte == b'\n')
        .filter(|line| !line.is_empty())
        .map(|line| {
            let before_tab = line
                .split(|byte| *byte == b'\t')
                .next()
                .ok_or_else(|| io::Error::other("cat-file tree line lacks tab"))?;
            let fields = before_tab.split(|byte| *byte == b' ').collect::<Vec<_>>();
            if fields.len() != 3 {
                return Err(io::Error::other("invalid cat-file tree line").into());
            }
            let kind = match fields[0] {
                b"100644" => ReferenceKind::Blob,
                b"100755" => ReferenceKind::Executable,
                b"120000" => ReferenceKind::Symlink,
                b"040000" => ReferenceKind::Tree,
                b"160000" => ReferenceKind::Gitlink,
                _ => return Err(io::Error::other("invalid cat-file tree mode").into()),
            };
            let oid = Oid::from_hex(fields[2])
                .ok_or_else(|| io::Error::other("invalid cat-file tree oid"))?;
            Ok((kind, oid))
        })
        .collect()
}

fn read_line(reader: &mut impl Read) -> Result<Vec<u8>> {
    let mut line = Vec::new();
    let mut byte = [0];
    loop {
        reader.read_exact(&mut byte)?;
        if byte[0] == b'\n' {
            return Ok(line);
        }
        line.push(byte[0]);
    }
}

fn parse_oid(bytes: &[u8]) -> Result<Oid> {
    let hex = bytes.strip_suffix(b"\n").unwrap_or(bytes);
    Oid::from_hex(hex).ok_or_else(|| io::Error::other("git emitted an invalid SHA-1").into())
}

fn oid_hex(oid: Oid) -> String {
    encode_hex(&oid.0)
}

fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    output
}

const fn kind_name(kind: ObjectKind) -> &'static str {
    match kind {
        ObjectKind::Blob => "blob",
        ObjectKind::Tree => "tree",
        ObjectKind::Commit => "commit",
    }
}

fn vector_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../kernel/tests/git_golden_oracle.txt")
}

fn op_vector_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../kernel/tests/ops_golden.txt")
}

fn encode_rle(bytes: &[u8]) -> String {
    let mut output = String::new();
    let mut index = 0;
    while index < bytes.len() {
        let byte = bytes[index];
        let mut end = index + 1;
        while end < bytes.len() && bytes[end] == byte {
            end += 1;
        }
        if !output.is_empty() {
            output.push(',');
        }
        output.push_str(&format!("{byte:02x}*{}", end - index));
        index = end;
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn real_repository_matches_git_and_jj_oracles() -> Result<()> {
        let report = generate(false)?;
        assert!(
            report.walked > 150,
            "fixture should walk a real object graph"
        );
        assert!(report.commits >= 12);
        assert!(report.trees >= 8);
        assert!(report.blobs >= 130);
        assert!((25..=60).contains(&report.curated));
        if Command::new("ssh-keygen").arg("-?").output().is_ok() {
            assert!(report.signed_commit);
        }
        eprintln!("oracle report: {report:?}");
        Ok(())
    }
}
